version: '3.1'

services:
  mongo:
    build: ./mongodb
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27777:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: Tutuacs
      MONGO_INITDB_ROOT_PASSWORD: Hubbe123
      MONGO_INITDB_ROOT_DATABASE: HubbeDb
    volumes:
      - ./mongodbdata:/data/db

  nest-app:
    build: .
    container_name: nest-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=mongodb://Tutuacs:Hubbe123@localhost:27777/HubbeDb
    depends_on:
      - mongodb

volumes:
    mongodb-volume:
